import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

const marvelFont = localFont({
  src: '../public/fonts/Marvel-Regular.ttf',
  variable: '--font-marvel',
});

const bebasNue = localFont({
  src: '../public/fonts/BebasNeue-Regular.ttf',
  variable: '--font-bebas-nue',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${marvelFont.variable} ${bebasNue.variable} antialiased`}>{children}</body>
    </html>
  );
}
