import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

const interFont = localFont({
  src: '../public/fonts/Inter_18pt-Regular.ttf',
  variable: '--font-inter',
});

const nunitoFont = localFont({
  src: '../public/fonts/Nunito-Regular.ttf',
  variable: '--font-nunito',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.variable} ${nunitoFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
